server:
  port: 8080

spring:
  application:
    name: spring-ai-mcp-server
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      client:
        base-url: https://api.openai.com
      model: gpt-4-turbo

logging:
  level:
    root: INFO
    com.example.springaimcpserver: DEBUG
    org.springframework.ai: INFO

# 엑셀/PPT 임시 파일 저장 경로
app:
  document:
    temp-dir: ${java.io.tmpdir}/spring-ai-mcp-server
